'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Download,
  Printer,
  FileText,
  FileSpreadsheet,
  File,
  X,
  Check,
  Loader2,
  Copy,
} from 'lucide-react';

interface ReportData {
  type: string;
  subject: string;
  timestamp: string;
  data: Record<string, unknown>;
  searchLinks?: Array<{ name: string; url: string; category?: string }>;
}

interface ReportExportProps {
  data: ReportData;
  onClose?: () => void;
}

export function ReportExport({ data, onClose }: ReportExportProps) {
  const [exporting, setExporting] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  // Generate formatted text report
  const generateTextReport = (): string => {
    const lines: string[] = [];
    const divider = '='.repeat(60);

    lines.push(divider);
    lines.push('SKIP TRACE REPORT');
    lines.push(divider);
    lines.push('');
    lines.push(`Subject: ${data.subject}`);
    lines.push(`Type: ${data.type.toUpperCase()}`);
    lines.push(`Generated: ${new Date(data.timestamp).toLocaleString()}`);
    lines.push('');
    lines.push(divider);
    lines.push('FINDINGS');
    lines.push(divider);
    lines.push('');

    // Format the data
    const formatValue = (value: unknown, indent: number = 0): string => {
      const prefix = '  '.repeat(indent);
      if (value === null || value === undefined) return '';
      if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
        return String(value);
      }
      if (Array.isArray(value)) {
        return value.map((v, i) => `${prefix}${i + 1}. ${formatValue(v, indent + 1)}`).join('\n');
      }
      if (typeof value === 'object') {
        return Object.entries(value)
          .filter(([, v]) => v !== null && v !== undefined && v !== '')
          .map(([k, v]) => {
            const formattedKey = k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase());
            if (typeof v === 'object' && !Array.isArray(v)) {
              return `${prefix}${formattedKey}:\n${formatValue(v, indent + 1)}`;
            }
            return `${prefix}${formattedKey}: ${formatValue(v, indent)}`;
          })
          .join('\n');
      }
      return String(value);
    };

    lines.push(formatValue(data.data));
    lines.push('');

    // Search links
    if (data.searchLinks && data.searchLinks.length > 0) {
      lines.push(divider);
      lines.push('SEARCH RESOURCES');
      lines.push(divider);
      lines.push('');

      const grouped = data.searchLinks.reduce((acc, link) => {
        const cat = link.category || 'Other';
        if (!acc[cat]) acc[cat] = [];
        acc[cat].push(link);
        return acc;
      }, {} as Record<string, typeof data.searchLinks>);

      for (const [category, links] of Object.entries(grouped)) {
        lines.push(`[${category}]`);
        for (const link of links) {
          lines.push(`  - ${link.name}: ${link.url}`);
        }
        lines.push('');
      }
    }

    lines.push(divider);
    lines.push('Generated by SkipTrace Pro');
    lines.push(divider);

    return lines.join('\n');
  };

  // Generate CSV
  const generateCSV = (): string => {
    const rows: string[][] = [];

    // Header info
    rows.push(['Skip Trace Report']);
    rows.push(['Subject', data.subject]);
    rows.push(['Type', data.type]);
    rows.push(['Generated', new Date(data.timestamp).toLocaleString()]);
    rows.push([]);

    // Flatten data for CSV
    const flattenObject = (obj: Record<string, unknown>, prefix = ''): Array<[string, string]> => {
      const result: Array<[string, string]> = [];

      for (const [key, value] of Object.entries(obj)) {
        const fullKey = prefix ? `${prefix}.${key}` : key;

        if (value === null || value === undefined) continue;

        if (Array.isArray(value)) {
          value.forEach((item, index) => {
            if (typeof item === 'object' && item !== null) {
              result.push(...flattenObject(item as Record<string, unknown>, `${fullKey}[${index}]`));
            } else {
              result.push([`${fullKey}[${index}]`, String(item)]);
            }
          });
        } else if (typeof value === 'object') {
          result.push(...flattenObject(value as Record<string, unknown>, fullKey));
        } else {
          result.push([fullKey, String(value)]);
        }
      }

      return result;
    };

    rows.push(['Field', 'Value']);
    const flatData = flattenObject(data.data);
    for (const [key, value] of flatData) {
      rows.push([key, value]);
    }

    // Search links
    if (data.searchLinks && data.searchLinks.length > 0) {
      rows.push([]);
      rows.push(['Search Resources']);
      rows.push(['Category', 'Name', 'URL']);
      for (const link of data.searchLinks) {
        rows.push([link.category || 'Other', link.name, link.url]);
      }
    }

    // Escape CSV values
    const escapeCSV = (val: string): string => {
      if (val.includes(',') || val.includes('"') || val.includes('\n')) {
        return `"${val.replace(/"/g, '""')}"`;
      }
      return val;
    };

    return rows.map(row => row.map(escapeCSV).join(',')).join('\n');
  };

  // Generate JSON
  const generateJSON = (): string => {
    return JSON.stringify({
      report: {
        subject: data.subject,
        type: data.type,
        generatedAt: data.timestamp,
        data: data.data,
        searchLinks: data.searchLinks,
      },
    }, null, 2);
  };

  // Download file
  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Handle export
  const handleExport = async (format: 'txt' | 'csv' | 'json') => {
    setExporting(format);

    // Simulate processing delay
    await new Promise(resolve => setTimeout(resolve, 500));

    const timestamp = new Date().toISOString().split('T')[0];
    const sanitizedSubject = data.subject.replace(/[^a-z0-9]/gi, '_').substring(0, 30);

    switch (format) {
      case 'txt':
        downloadFile(
          generateTextReport(),
          `skiptrace_${sanitizedSubject}_${timestamp}.txt`,
          'text/plain'
        );
        break;
      case 'csv':
        downloadFile(
          generateCSV(),
          `skiptrace_${sanitizedSubject}_${timestamp}.csv`,
          'text/csv'
        );
        break;
      case 'json':
        downloadFile(
          generateJSON(),
          `skiptrace_${sanitizedSubject}_${timestamp}.json`,
          'application/json'
        );
        break;
    }

    setExporting(null);
  };

  // Handle print
  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const styles = `
      <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; }
        h1 { color: #0891b2; border-bottom: 2px solid #0891b2; padding-bottom: 10px; }
        h2 { color: #334155; margin-top: 30px; }
        .meta { color: #64748b; margin-bottom: 20px; }
        .section { margin: 20px 0; padding: 15px; background: #f8fafc; border-radius: 8px; }
        .label { font-weight: bold; color: #334155; }
        .value { color: #475569; }
        .link { color: #0891b2; text-decoration: none; }
        .category { font-weight: bold; margin-top: 15px; color: #475569; }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        th, td { text-align: left; padding: 8px; border-bottom: 1px solid #e2e8f0; }
        th { background: #f1f5f9; }
        @media print { body { padding: 20px; } }
      </style>
    `;

    const formatDataForPrint = (obj: unknown, level = 0): string => {
      if (obj === null || obj === undefined) return '';
      if (typeof obj === 'string' || typeof obj === 'number' || typeof obj === 'boolean') {
        return String(obj);
      }
      if (Array.isArray(obj)) {
        if (obj.length === 0) return 'None';
        return `<ul>${obj.map(item => `<li>${formatDataForPrint(item, level + 1)}</li>`).join('')}</ul>`;
      }
      if (typeof obj === 'object') {
        const entries = Object.entries(obj).filter(([, v]) => v !== null && v !== undefined && v !== '');
        if (entries.length === 0) return 'None';
        return `<table>${entries.map(([k, v]) => {
          const label = k.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase());
          return `<tr><td class="label">${label}</td><td class="value">${formatDataForPrint(v, level + 1)}</td></tr>`;
        }).join('')}</table>`;
      }
      return String(obj);
    };

    const searchLinksHtml = data.searchLinks && data.searchLinks.length > 0
      ? `<h2>Search Resources</h2>
         ${Object.entries(data.searchLinks.reduce((acc, link) => {
           const cat = link.category || 'Other';
           if (!acc[cat]) acc[cat] = [];
           acc[cat].push(link);
           return acc;
         }, {} as Record<string, typeof data.searchLinks>)).map(([category, links]) => `
           <div class="category">${category}</div>
           <ul>${links.map(link => `<li><a href="${link.url}" class="link">${link.name}</a></li>`).join('')}</ul>
         `).join('')}`
      : '';

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Skip Trace Report - ${data.subject}</title>
          ${styles}
        </head>
        <body>
          <h1>Skip Trace Report</h1>
          <div class="meta">
            <p><strong>Subject:</strong> ${data.subject}</p>
            <p><strong>Type:</strong> ${data.type.toUpperCase()}</p>
            <p><strong>Generated:</strong> ${new Date(data.timestamp).toLocaleString()}</p>
          </div>
          <h2>Findings</h2>
          <div class="section">
            ${formatDataForPrint(data.data)}
          </div>
          ${searchLinksHtml}
          <p style="margin-top: 40px; color: #94a3b8; font-size: 12px;">
            Generated by SkipTrace Pro
          </p>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 250);
  };

  // Copy to clipboard
  const handleCopy = async () => {
    await navigator.clipboard.writeText(generateTextReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-white/5 border border-white/10 rounded-xl p-4">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-white font-medium">Export Report</h3>
        {onClose && (
          <button onClick={onClose} className="p-1 hover:bg-white/10 rounded">
            <X className="w-4 h-4 text-white/50" />
          </button>
        )}
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {/* Text Export */}
        <button
          onClick={() => handleExport('txt')}
          disabled={exporting !== null}
          className="p-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg transition-colors flex flex-col items-center gap-2 disabled:opacity-50"
        >
          {exporting === 'txt' ? (
            <Loader2 className="w-6 h-6 text-cyan-400 animate-spin" />
          ) : (
            <FileText className="w-6 h-6 text-cyan-400" />
          )}
          <span className="text-xs text-white">Text (.txt)</span>
        </button>

        {/* CSV Export */}
        <button
          onClick={() => handleExport('csv')}
          disabled={exporting !== null}
          className="p-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg transition-colors flex flex-col items-center gap-2 disabled:opacity-50"
        >
          {exporting === 'csv' ? (
            <Loader2 className="w-6 h-6 text-green-400 animate-spin" />
          ) : (
            <FileSpreadsheet className="w-6 h-6 text-green-400" />
          )}
          <span className="text-xs text-white">CSV (.csv)</span>
        </button>

        {/* JSON Export */}
        <button
          onClick={() => handleExport('json')}
          disabled={exporting !== null}
          className="p-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg transition-colors flex flex-col items-center gap-2 disabled:opacity-50"
        >
          {exporting === 'json' ? (
            <Loader2 className="w-6 h-6 text-yellow-400 animate-spin" />
          ) : (
            <File className="w-6 h-6 text-yellow-400" />
          )}
          <span className="text-xs text-white">JSON (.json)</span>
        </button>

        {/* Print */}
        <button
          onClick={handlePrint}
          className="p-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg transition-colors flex flex-col items-center gap-2"
        >
          <Printer className="w-6 h-6 text-purple-400" />
          <span className="text-xs text-white">Print</span>
        </button>
      </div>

      {/* Copy to Clipboard */}
      <button
        onClick={handleCopy}
        className="mt-3 w-full p-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg transition-colors flex items-center justify-center gap-2"
      >
        {copied ? (
          <>
            <Check className="w-4 h-4 text-green-400" />
            <span className="text-sm text-green-400">Copied to clipboard!</span>
          </>
        ) : (
          <>
            <Copy className="w-4 h-4 text-white/50" />
            <span className="text-sm text-white/70">Copy to Clipboard</span>
          </>
        )}
      </button>
    </div>
  );
}

// Quick export button for inline use
export function QuickExportButton({ data }: { data: ReportData }) {
  const [showMenu, setShowMenu] = useState(false);

  return (
    <div className="relative">
      <button
        onClick={() => setShowMenu(!showMenu)}
        className="p-2 hover:bg-white/10 rounded-lg transition-colors flex items-center gap-2"
      >
        <Download className="w-4 h-4 text-white/50" />
        <span className="text-sm text-white/70">Export</span>
      </button>

      <AnimatePresence>
        {showMenu && (
          <>
            <div className="fixed inset-0 z-40" onClick={() => setShowMenu(false)} />
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="absolute right-0 top-full mt-2 z-50 w-64"
            >
              <ReportExport data={data} onClose={() => setShowMenu(false)} />
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
}
