import { z } from "zod";

// Research query from user
export const ResearchQuery = z.object({
  query: z.string(),
  filters: z.object({
    industry: z.string().optional(),
    fundingStage: z.string().optional(),
    employeeRange: z.tuple([z.number(), z.number()]).optional(),
    techStack: z.array(z.string()).optional(),
    signals: z.array(z.string()).optional(),
    location: z.string().optional(),
  }).optional(),
  maxResults: z.number().default(20),
});
export type ResearchQuery = z.infer<typeof ResearchQuery>;

// Parsed intent from the query
export const ParsedIntent = z.object({
  originalQuery: z.string(),
  understanding: z.string(), // Human-readable understanding
  criteria: z.object({
    companyType: z.string().optional(), // "B2B SaaS", "fintech", etc.
    fundingStage: z.array(z.string()).optional(), // ["seed", "series_a"]
    employeeRange: z.tuple([z.number(), z.number()]).optional(),
    techStack: z.array(z.string()).optional(),
    hiringSignals: z.object({
      departments: z.array(z.string()).optional(),
      seniorities: z.array(z.string()).optional(),
      isFirstHire: z.boolean().optional(),
      minOpenings: z.number().optional(),
    }).optional(),
    otherSignals: z.array(z.string()).optional(),
    recency: z.string().optional(), // "last 6 months", "recent"
  }),
  confidence: z.number().min(0).max(1),
});
export type ParsedIntent = z.infer<typeof ParsedIntent>;

// Research plan generated by the thinking model
export const ResearchPlan = z.object({
  id: z.string(),
  intent: ParsedIntent,
  steps: z.array(z.object({
    id: z.string(),
    type: z.enum(["crawl_jobs", "search_funding", "search_news", "enrich_company", "filter", "rank"]),
    description: z.string(),
    source: z.string().optional(),
    params: z.record(z.string(), z.unknown()),
    dependsOn: z.array(z.string()).optional(),
  })),
  estimatedTime: z.number(), // seconds
  createdAt: z.string(),
});
export type ResearchPlan = z.infer<typeof ResearchPlan>;

// Execution step status
export const StepStatus = z.enum(["pending", "running", "completed", "failed", "skipped"]);
export type StepStatus = z.infer<typeof StepStatus>;

// Research execution state
export const ResearchExecution = z.object({
  planId: z.string(),
  status: z.enum(["planning", "executing", "reasoning", "completed", "failed"]),
  currentStep: z.string().optional(),
  steps: z.record(z.string(), z.object({
    status: StepStatus,
    startedAt: z.string().optional(),
    completedAt: z.string().optional(),
    result: z.unknown().optional(),
    error: z.string().optional(),
  })),
  intermediateResults: z.object({
    companiesFound: z.number(),
    signalsFound: z.number(),
    candidatesAfterFilter: z.number(),
  }),
  startedAt: z.string(),
  completedAt: z.string().optional(),
});
export type ResearchExecution = z.infer<typeof ResearchExecution>;

// Reasoning about a candidate
export const CandidateReasoning = z.object({
  companyDomain: z.string(),
  companyName: z.string(),
  score: z.number().min(0).max(100),
  confidence: z.enum(["high", "medium", "low"]),
  matchedCriteria: z.array(z.object({
    criterion: z.string(),
    evidence: z.string(),
    source: z.string(),
    sourceUrl: z.string().optional(),
  })),
  unmatchedCriteria: z.array(z.string()),
  whyNow: z.string(), // The key insight
  reasoning: z.string(), // Full reasoning explanation
  risks: z.array(z.string()).optional(),
});
export type CandidateReasoning = z.infer<typeof CandidateReasoning>;

// Final research result
export const ResearchResult = z.object({
  id: z.string(),
  query: ResearchQuery,
  intent: ParsedIntent,
  execution: ResearchExecution,
  candidates: z.array(CandidateReasoning),
  summary: z.object({
    totalFound: z.number(),
    qualified: z.number(),
    topSignals: z.array(z.string()),
    commonTechStack: z.array(z.string()),
    insights: z.array(z.string()),
  }),
  completedAt: z.string(),
  duration: z.number(), // ms
});
export type ResearchResult = z.infer<typeof ResearchResult>;

// Thinking step for UI display
export const ThinkingStep = z.object({
  id: z.string(),
  type: z.enum(["understanding", "planning", "searching", "analyzing", "reasoning", "complete"]),
  status: StepStatus,
  title: z.string(),
  description: z.string(),
  progress: z.number().min(0).max(100).optional(),
  details: z.array(z.string()).optional(),
  startedAt: z.string().optional(),
  completedAt: z.string().optional(),
});
export type ThinkingStep = z.infer<typeof ThinkingStep>;

// Stream of thinking updates
export type ThinkingUpdate = {
  type: "step_started" | "step_progress" | "step_completed" | "step_failed" | "result";
  stepId?: string;
  data: ThinkingStep | ResearchResult | { progress: number; detail: string };
};
